# Generated by Django 3.2.8 on 2021-10-22 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 22, 8, 29, 9, 177609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 22, 8, 29, 9, 177585, tzinfo=utc)),
        ),
    ]
