# Generated by Django 3.2.7 on 2021-10-23 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20211022_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='file_upload',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 23, 13, 23, 8, 187352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 23, 13, 23, 8, 187320, tzinfo=utc)),
        ),
    ]
